### PR TITLE
fix homebridge 1.0.0 crash

### PR DESCRIPTION
**Pull request by geilername**
this quick and dirty fix should be compatible with homebridge 1.0.0

### CODE REVIEW

**Comment by 19kirk79** [comment]
besten Dank!!!

**Comment by keuninkske** [comment]
maaanyyyy thanks!!
i would like to try it
but don't know how to install your version before it is merged by lumoc or sroose
can someone help me?

**Comment by geilername** [comment]
@keuninkske it should be sufficent to just change the one line in your node-modules/homebridge-loxone.... folder like in the changes. on phone currently so i cant really copy it over.

**Comment by keuninkske** [comment]
just did my first time text editing from linux terminal
google helped me a bit with that

but your help is mighty!! got it finaly startin up without failures
thanks alot!

ps: i should learn more about this stuff

**Comment by Lumoc** [comment]
@geilername thanks - regenerating the NPM Package

**Pull request merged**
